Adding database connections chapter
plotly/dash-docs pull request #1030
Opened 2020-11-24 09:45 UTC by HammadTheOne

This PR complements plotly/dash-enterprise-docs#632 by adding a chapter on Database Connections with Dash apps. The page highlights some of the "best practices" used within the SQL template apps, and some more relevant documentation. 

Once this is merged, a git tag will be created, and the version of `dash-docs` in `dash-enterprise-docs` will be updated as well. 

Relevant Pages to Visit:
http://127.0.0.1:8060/dash-enterprise/database-connections

Post-merge checklist:

The master branch is auto-deployed to `dash.plotly.com`.
Once you have merged your PR, wait 5-10 minutes and check dash.plotly.com
to verify that your changes have been made.

- [ ] I understand

2020-11-24 20:26 UTC, rpkyle requested changes
Overall this looks helpful, and a nice addition to the docs! Just a couple questions about trying to clarify the language a bit more, and once resolved I'd be comfortable merging this one in.

2020-11-24 20:26 UTC, rpkyle commented on dash_docs/chapter_index.py
> +                    'name': 'Dash App SQL Database Connections',
Given that most of the other entries in this section appear to include action verbs to start, what if we did something similar here?

```suggestion
                    'name': 'Connect a Dash App to an SQL Database',
```

2020-11-24 20:26 UTC, rpkyle commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +    Dash Apps can use open source libraries in the Python ecosystem to query external databases and datastores in callbacks or job queues.
If the content here is (or will eventually be) useful to R and Julia users, it might be good to omit the "in the Python ecosystem" bit.

```suggestion
    Dash Apps can use open source libraries to query external databases and datastores in callbacks or job queues.
```

2020-11-24 20:26 UTC, rpkyle commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +    For complete example, see the "Database Connections" section in Sample Apps & Templates:
```suggestion
    For complete examples, see the relevant "Database Connections" section in Sample Apps & Templates:
```

2020-11-24 20:26 UTC, rpkyle commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +    4. Poll the database initially to check that it is ready to begin accepting connections. We can create a simple
Instead of using "poll the database" here, I wonder if we could simplify the language a bit to avoid jargon. Also, I think we're actually testing multiple things in this step:

```suggestion
    4. Test that the database server has started successfully, verify that it is accepting connections, and validate the credentials and connection string; we can create a simple
```

2020-11-24 20:26 UTC, rpkyle commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +    to the database itself and differentiate them from the Dash app callbacks. Eg:
Is it possible to elaborate on what "differentiate them from the Dash app callbacks" means here? 

If I understood correctly, I think the gist is that we want to be able to to isolate issues arising from errors in the callback logic vs. those caused by database configuration or connectivity problems.

2020-11-24 20:26 UTC, rpkyle commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +        'postgresql+psycopg2://scott:tiger@localhost/test',
I've never used SQLAlchemy, but what does `scott:tiger@localhost/test` reference here? Is this related to the default user and database name?

2020-11-24 20:26 UTC, rpkyle commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +        'postgresql+psycopg2://scott:tiger@localhost/test',
Ah, now I think I understand -- do we want to change this to something like `postgresql+psycopg2://username:password@localhost/database`?

2020-11-24 22:26 UTC, HammadTheOne commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +        'postgresql+psycopg2://scott:tiger@localhost/test',
Fixed in b13cda4

2020-11-24 22:26 UTC, HammadTheOne commented on dash_docs/chapters/dash_enterprise/dash_enterprise_chapters.py
> +    to the database itself and differentiate them from the Dash app callbacks. Eg:
Updated in b13cda4

2020-11-26 00:17 UTC, HammadTheOne commented
After checking out these chapters within the DE docs, it seems we need to make some changes to accommodate the following commit: https://github.com/plotly/dash-docs/commit/dd816aa60d38bad75ee2bde35ed0ac9c64f5e11a.

The `dash-enterprise` chapter no longer has the tiled format, and instead has a list format:
![image](https://user-images.githubusercontent.com/30986043/100293743-ad860f80-2f52-11eb-9914-6c8a868ca7ca.png)

I'm going to investigate a little more and get a fix in for this because it seems unintentional.

2020-11-26 22:22 UTC, rpkyle approved these changes
I can't speak to the list vs. tile format issue, but the rest of the changes here look good to me. :woman_dancing:

2020-11-29 00:03 UTC, merged