Add dash-vtk chapter
plotly/dash-docs pull request #1091
Opened 2021-02-04 00:48 UTC by xhlulu

Post-merge checklist:

The master branch is auto-deployed to `dash.plotly.com`.
Once you have merged your PR, wait 5-10 minutes and check dash.plotly.com
to verify that your changes have been made.

- [ ] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If this PR adds an image or animated GIF:
- [ ] This image was saved and referenced locally rather than via an external link

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I considered whether I could replace the `dcc.Markdown` call with `rc.Markdown`, which will replace relative links with `tools.relpath` internally. Otherwise, I used e.g. `<dccLink href=tools.relpath('/layout') children="the first chapter"/>` instead of `[the first chapter](/layout)` (importing `tools` from `dash_docs`), and set `dangerously_allow_html=true` in the `dcc.Markdown` call.

If I changed the `chapter_index` by removing or relocating a page:
- [ ] I added a redirect in `dash_docs/server.py` from the old URL to the new URL

2021-02-04 00:51 UTC, xhlulu commented
@jourdain If there's anything you'd like to modify, could you update `dash_docs/chapters/dash_vtk/index.py` directly? We can port them back later after this PR is merged.

2021-02-04 15:09 UTC, jourdain commented on dash_docs/chapters/dash_vtk/__init__.py
> +    index.layout = html.Div("Dash Slicer is not supported on Python 2.7")
Dash VTK

2021-02-04 15:13 UTC, jourdain approved these changes
LGTM but also eager to see it live on your website

2021-02-04 15:49 UTC, xhlulu commented
Seems like i'm getting this error in the tests:
```
――――――――――――――――――――――――――― test_sitemap_is_updated ――――――――――――――――――――――――――――

    @pytest.mark.skipif(sys.version_info < (3, 6), reason="requires python3.6 or higher")
    def test_sitemap_is_updated():
        from generate_sitemap import create_sitemap
        with open('dash_docs/assets/sitemap.xml', 'r') as f:
            saved_sitemap = f.read()
>       assert create_sitemap() == saved_sitemap
E       AssertionError: assert '<urlset xmln...\n</urlset>\n' == '<urlset xmln...\n</urlset>\n'
E         Skipping 20872 identical leading characters in diff, use -v to show
E           >
E           </url>
E         + <url>
E         +     <loc>https://dash.plotly.com/vtk</loc>
E         + </url>
E           </urlset>

tests/unit/test_sitemap.py:9: AssertionError

 tests/unit/test_sitemap.py ⨯                                    100% ██████████
=============================== warnings summary ===============================
dash_docs/convert_to_html.py:32
  /home/circleci/project/dash_docs/convert_to_html.py:32: DeprecationWarning:
  
  invalid escape sequence \s
```

and it's preventing the heroku app from booting. Any idea about the cause @plotly/customer-success ?

2021-02-04 20:40 UTC, xhlulu commented
Seems like the deployment is failing. @chriddyp any idea why that might be happening (tests all passed and works locally)

2021-02-04 20:45 UTC, chriddyp commented
@xhlulu - What do the Heroku logs say?

2021-02-04 20:55 UTC, xhlulu commented
This is the build logs: https://dashboard.heroku.com/apps/dash-docs-pr-1091/activity/builds/4f10bc8a-eca4-4f66-84f4-98afe24034eb

Here's the ending: 
```
       Successfully built dash-user-guide-components
       Installing collected packages: pip, dash-user-guide-components
         Attempting uninstall: pip
           Found existing installation: pip 20.1.1
           Uninstalling pip-20.1.1:
             Successfully uninstalled pip-20.1.1
         Attempting uninstall: dash-user-guide-components
           Found existing installation: dash-user-guide-components 0.0.3
           Uninstalling dash-user-guide-components-0.0.3:
             Successfully uninstalled dash-user-guide-components-0.0.3
       Successfully installed dash-user-guide-components-0.0.3 pip-20.0.2
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 489.5M
-----> Launching...
 !     Warning: Your slug size (489 MB) exceeds our soft limit (300 MB) which may affect boot time.
       Released v11
       https://dash-docs-pr-1091.herokuapp.com/ deployed to Heroku
```

I haven't used heroku CLI in years so i'll figure that out

2021-02-04 20:56 UTC, jackparmer commented
@jonmmease & @empet may be interested in scanning this as well (Jon b/c he wrote the Holoviews integration chapter and Emilia because she has prior experience with VTK + Plotly.py)

2021-02-04 21:01 UTC, xhlulu commented
Ok so I've monitored the application logs a bit and found that: 
```
2021-02-04T21:00:22.451700+00:00 app[web.1]:   File "/app/index.py", line 3, in <module>
2021-02-04T21:00:22.451700+00:00 app[web.1]:     from dash_docs.run import app, server
2021-02-04T21:00:22.451700+00:00 app[web.1]:   File "/app/dash_docs/run.py", line 10, in <module>
2021-02-04T21:00:22.451701+00:00 app[web.1]:     from .import chapter_index
2021-02-04T21:00:22.451701+00:00 app[web.1]:   File "/app/dash_docs/chapter_index.py", line 3, in <module>
2021-02-04T21:00:22.451701+00:00 app[web.1]:     from .import chapters
2021-02-04T21:00:22.451702+00:00 app[web.1]:   File "/app/dash_docs/chapters/__init__.py", line 15, in <module>
2021-02-04T21:00:22.451702+00:00 app[web.1]:     from .import dash_vtk
2021-02-04T21:00:22.451703+00:00 app[web.1]:   File "/app/dash_docs/chapters/dash_vtk/__init__.py", line 6, in <module>
2021-02-04T21:00:22.451736+00:00 app[web.1]:     from .import index
2021-02-04T21:00:22.451740+00:00 app[web.1]:   File "/app/dash_docs/chapters/dash_vtk/index.py", line 9, in <module>
2021-02-04T21:00:22.452342+00:00 app[web.1]:     examples = tools.load_examples(__file__)
2021-02-04T21:00:22.452366+00:00 app[web.1]:   File "/app/dash_docs/tools.py", line 78, in load_examples
2021-02-04T21:00:22.452676+00:00 app[web.1]:     examples[filename] = load_example(full_filename, run=run)
2021-02-04T21:00:22.452679+00:00 app[web.1]:   File "/app/dash_docs/tools.py", line 43, in wrapper
2021-02-04T21:00:22.452978+00:00 app[web.1]:     raise e
2021-02-04T21:00:22.452979+00:00 app[web.1]:   File "/app/dash_docs/tools.py", line 40, in wrapper
2021-02-04T21:00:22.453235+00:00 app[web.1]:     return func(path, **kwargs)
2021-02-04T21:00:22.453254+00:00 app[web.1]:   File "/app/dash_docs/tools.py", line 219, in load_example
2021-02-04T21:00:22.453610+00:00 app[web.1]:     raise e
2021-02-04T21:00:22.453611+00:00 app[web.1]:   File "/app/dash_docs/tools.py", line 216, in load_example
2021-02-04T21:00:22.453948+00:00 app[web.1]:     exec(_example, scope)
2021-02-04T21:00:22.453973+00:00 app[web.1]:   File "<string>", line 5, in <module>
2021-02-04T21:00:22.454176+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/dash_vtk/utils/__init__.py", line 1, in <module>
2021-02-04T21:00:22.454283+00:00 app[web.1]:     from .vtk import to_mesh_state, to_volume_state, presets, preset_as_options
2021-02-04T21:00:22.454286+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/dash_vtk/utils/vtk.py", line 3, in <module>
2021-02-04T21:00:22.454397+00:00 app[web.1]:     import vtk
2021-02-04T21:00:22.454398+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/vtk.py", line 30, in <module>
2021-02-04T21:00:22.454489+00:00 app[web.1]:     all_m = importlib.import_module('vtkmodules.all')
2021-02-04T21:00:22.454503+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
2021-02-04T21:00:22.454625+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-02-04T21:00:22.454629+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/vtkmodules/all.py", line 29, in <module>
2021-02-04T21:00:22.454748+00:00 app[web.1]:     from .vtkRenderingOpenGL2 import *
2021-02-04T21:00:22.454749+00:00 app[web.1]: ImportError: libGL.so.1: cannot open shared object file: No such file or directory
2021-02-04T21:00:22.849213+00:00 heroku[web.1]: Process exited with status 1
```

That's very similar to an error that i had before and it's caused by an `apt-package` missing. I'll add that

2021-02-04 21:05 UTC, jourdain commented
Normally we should not need libGL.so.1 maybe I should import only the part of VTK that I need to prevent the "load all" from happening since we don't want to load the rendering part of the server side.

2021-02-04 21:14 UTC, jourdain commented
I just pushed a "fix" on dash-vtk

```
commit a7fc126f31a3e182b18242d84865ead5cc77a6f0 (HEAD -> master, origin/master)
Author: Sebastien Jourdain <sebastien.jourdain@kitware.com>
Date:   Thu Feb 4 14:12:32 2021 -0700

    simplify vtk import

diff --git a/dash_vtk/utils/vtk.py b/dash_vtk/utils/vtk.py
index 5ddd878..3e1ab19 100644
--- a/dash_vtk/utils/vtk.py
+++ b/dash_vtk/utils/vtk.py
@@ -1,7 +1,7 @@
 import dash_vtk
 
-import vtk
 from vtk.util.numpy_support import vtk_to_numpy
+from vtk.vtkFiltersGeometry import vtkGeometryFilter
 
 # Numpy to JS TypedArray
 to_js_type = {
@@ -28,7 +28,7 @@ def to_mesh_state(dataset, field_to_keep=None):
   if dataset.IsA('vtkPolyData'):
     polydata = dataset
   else:
-    extractSkinFilter = vtk.vtkGeometryFilter()
+    extractSkinFilter = vtkGeometryFilter()
     extractSkinFilter.SetInputData(dataset)
     extractSkinFilter.Update()
     polydata = extractSkinFilter.GetOutput()
```

2021-02-04 21:20 UTC, jourdain commented
Also 

```
commit 11535bf8031a7dab4cc0e2d2629b3c2e9ad8f1f3 (HEAD -> master, origin/master)
Author: Sebastien Jourdain <sebastien.jourdain@kitware.com>
Date:   Thu Feb 4 14:18:58 2021 -0700

    Update import vtk to only pick the module we use

diff --git a/docs/README.md b/docs/README.md
index 58c1fb6..612df2b 100644
--- a/docs/README.md
+++ b/docs/README.md
@@ -146,10 +146,10 @@ import dash_html_components as html
 import dash_vtk
 from dash_vtk.utils import to_volume_state
 
-import vtk
+from vtk.vtkImagingCore import vtkRTAnalyticSource
 
 # Use VTK to get some data
-data_source = vtk.vtkRTAnalyticSource()
+data_source = vtkRTAnalyticSource()
 data_source.Update()  # <= Execute source to produce an output
 dataset = data_source.GetOutput()
 
@@ -745,10 +745,10 @@ import dash_html_components as html
 import dash_vtk
 from dash_vtk.utils import to_volume_state
 
-import vtk
+from vtk.vtkImagingCore import vtkRTAnalyticSource
 
 # Use VTK to get some data
-data_source = vtk.vtkRTAnalyticSource()
+data_source = vtkRTAnalyticSource()
 data_source.Update()  # <= Execute source to produce an output
 dataset = data_source.GetOutput()
```

2021-02-04 22:42 UTC, xhlulu commented
I released a new version of dash-vtk so now it should boot up correctly. Thanks @jourdain for making the changes

2021-02-04 22:43 UTC, jourdain commented
Let me know once it is up so I can see what it looks like once live. Thx

2021-02-04 22:54 UTC, xhlulu commented
Getting this error now:
```
2021-02-04T22:47:56.036816+00:00 app[web.1]:     from vtk.util.numpy_support import vtk_to_numpy
2021-02-04T22:47:56.036835+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/vtk/__init__.py", line 12, in <module>
2021-02-04T22:47:56.036964+00:00 app[web.1]:     from .vtkOpenGLKit import *
2021-02-04T22:47:56.036968+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/vtk/vtkOpenGLKit.py", line 9, in <module>
2021-02-04T22:47:56.037253+00:00 app[web.1]:     from vtkOpenGLKitPython import *
2021-02-04T22:47:56.037287+00:00 app[web.1]: ModuleNotFoundError: No module named 'vtkOpenGLKitPython'
2021-02-04T22:47:56.530402+00:00 heroku[web.1]: Process exited with status 1
2021-02-04T22:47:56.570975+00:00 heroku[web.1]: State changed from starting to crashed
2021-02-04T22:51:23.095225+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=dash-docs-pr-1091.herokuapp.com request_id=56e55c8f-e3d2-4d50-a09b-f0e991df0843 fwd="160.32.220.130" dyno= connect= service= status=503 bytes= protocol=https
2021-02-04T22:51:23.267558+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=dash-docs-pr-1091.herokuapp.com request_id=25af55dc-041b-4c80-b3f4-29decabf5c8e fwd="160.32.220.130" dyno= connect= service= status=503 bytes= protocol=https
```

2021-02-04 23:02 UTC, jourdain commented
Can you try to pip install a vtk 8 rather than 9?

2021-02-04 23:07 UTC, xhlulu commented
@jourdain It's already v8:
```
       Collecting vtk==8.1.*
         Downloading vtk-8.1.2-cp37-cp37m-manylinux1_x86_64.whl (48.9 MB)
```
Can't use vtk-9 due to the buildpacks anyway

2021-02-04 23:20 UTC, jourdain commented
Try to replace 

`from vtk.util.numpy_support import vtk_to_numpy`

by 

`vtkmodules.util.numpy_support import vtk_to_numpy`

2021-02-04 23:22 UTC, xhlulu commented
> Try to replace
> 
> `from vtk.util.numpy_support import vtk_to_numpy`
> 
> by
> 
> `vtkmodules.util.numpy_support import vtk_to_numpy`

Where is that in the code?

2021-02-04 23:24 UTC, jcfr commented
After creating a virtual env with python 3.6, I was not able to reproduce the problem. 

Here is what I did:

```bash
$ mkvirtualenv -p python3.6 test-vtk-install
[...]

(test-vtk-install) $ pip install vtk==8.1.2
Collecting vtk==8.1.2
  Downloading vtk-8.1.2-cp36-cp36m-manylinux1_x86_64.whl (48.9 MB)
[...]
Successfully installed vtk-8.1.2

(test-vtk-install) $ pip install numpy
Collecting numpy
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
[...]
Successfully installed numpy-1.19.5

(test-vtk-install) $ python
```

```python
>>> import vtk
>>> from vtk.util.numpy_support import vtk_to_numpy
>>> from vtk.vtkOpenGLKit import *
```

@xhlulu  Do you have a way to list all files installed in the `/path/to/site-packages/vtk` directory ?

2021-02-04 23:26 UTC, xhlulu commented
@jcfr seems like the circleci tests are passing but the heroku build is not, so I think the problem is with the heroku buildpacks we are using (I've seen similar problems when deploying to dash-playground.plotly.host)

2021-02-04 23:26 UTC, jourdain commented
https://github.com/plotly/dash-vtk/blob/master/dash_vtk/utils/vtk.py#L3

2021-02-04 23:27 UTC, xhlulu commented
> Do you have a way to list all files installed in the /path/to/site-packages/vtk directory ?

I'm not actually sure how heroku handles pip installations, so i'm not sure where to find the installed vtk packages.

2021-02-04 23:43 UTC, xhlulu commented
@jourdain Doesn't work. See [circleci logs](https://app.circleci.com/pipelines/github/plotly/dash-vtk/70/workflows/5f43db1f-a4f5-4f80-b659-17f23fca99e9/jobs/203):
```
    import dash_vtk
    
>   from vtkmodules.util.numpy_support import vtk_to_numpy
E   ModuleNotFoundError: No module named 'vtkmodules'
```

2021-02-05 00:01 UTC, xhlulu commented
Failed again. Full log here:
<details><summary>Open logs</summary>
<p>

```
2021-02-04T23:57:54.993305+00:00 app[web.1]: /app/.heroku/python/lib/python3.7/site-packages/scipy/__init__.py:137: UserWarning:
2021-02-04T23:57:54.993343+00:00 app[web.1]: 
2021-02-04T23:57:54.993344+00:00 app[web.1]: NumPy 1.16.5 or above is required for this version of SciPy (detected version 1.16.2)
2021-02-04T23:57:54.993344+00:00 app[web.1]: 
2021-02-04T23:57:57.592625+00:00 app[web.1]: /app/.heroku/python/lib/python3.7/site-packages/plotly/tools.py:465: DeprecationWarning:
2021-02-04T23:57:57.592657+00:00 app[web.1]: 
2021-02-04T23:57:57.592658+00:00 app[web.1]: plotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead
2021-02-04T23:57:57.592658+00:00 app[web.1]: 
2021-02-04T23:58:12.325008+00:00 app[web.1]: import dash
2021-02-04T23:58:12.325022+00:00 app[web.1]: import dash_html_components as html
2021-02-04T23:58:12.325023+00:00 app[web.1]: 
2021-02-04T23:58:12.325023+00:00 app[web.1]: import dash_vtk
2021-02-04T23:58:12.325023+00:00 app[web.1]: from dash_vtk.utils import to_volume_state
2021-02-04T23:58:12.325024+00:00 app[web.1]: 
2021-02-04T23:58:12.325025+00:00 app[web.1]: from vtk.vtkImagingCore import vtkRTAnalyticSource
2021-02-04T23:58:12.325025+00:00 app[web.1]: 
2021-02-04T23:58:12.325026+00:00 app[web.1]: # Use VTK to get some data
2021-02-04T23:58:12.325027+00:00 app[web.1]: data_source = vtkRTAnalyticSource()
2021-02-04T23:58:12.325027+00:00 app[web.1]: data_source.Update()  # <= Execute source to produce an output
2021-02-04T23:58:12.325027+00:00 app[web.1]: dataset = data_source.GetOutput()
2021-02-04T23:58:12.325028+00:00 app[web.1]: 
2021-02-04T23:58:12.325029+00:00 app[web.1]: # Use helper to get a volume structure that can be passed as-is to a Volume
2021-02-04T23:58:12.325029+00:00 app[web.1]: volume_state = to_volume_state(dataset)  # No need to select field
2021-02-04T23:58:12.325030+00:00 app[web.1]: 
2021-02-04T23:58:12.325030+00:00 app[web.1]: content = dash_vtk.View([
2021-02-04T23:58:12.325030+00:00 app[web.1]:     dash_vtk.VolumeRepresentation([
2021-02-04T23:58:12.325031+00:00 app[web.1]:         # GUI to control Volume Rendering
2021-02-04T23:58:12.325031+00:00 app[web.1]:         # + Setup good default at startup
2021-02-04T23:58:12.325032+00:00 app[web.1]:         dash_vtk.VolumeController(),
2021-02-04T23:58:12.325032+00:00 app[web.1]:         # Actual volume
2021-02-04T23:58:12.325032+00:00 app[web.1]:         dash_vtk.Volume(state=volume_state),
2021-02-04T23:58:12.325033+00:00 app[web.1]:     ]),
2021-02-04T23:58:12.325033+00:00 app[web.1]: ])
2021-02-04T23:58:12.325033+00:00 app[web.1]: 
2021-02-04T23:58:12.325034+00:00 app[web.1]: # Dash setup
2021-02-04T23:58:12.325034+00:00 app[web.1]: # app = dash.Dash(__name__)
2021-02-04T23:58:12.325034+00:00 app[web.1]: server = app.server
2021-02-04T23:58:12.325035+00:00 app[web.1]: 
2021-02-04T23:58:12.325035+00:00 app[web.1]: layout = html.Div(
2021-02-04T23:58:12.325035+00:00 app[web.1]:     style={"width": "100%", "height": "400px"},
2021-02-04T23:58:12.325036+00:00 app[web.1]:     children=[content],
2021-02-04T23:58:12.325036+00:00 app[web.1]: )
2021-02-04T23:58:12.325036+00:00 app[web.1]: 
2021-02-04T23:58:12.325037+00:00 app[web.1]: if __name__ == "__main__":print("Running")
2021-02-04T23:58:12.325037+00:00 app[web.1]:     # app.run_server(debug=True)
2021-02-04T23:58:12.325038+00:00 app[web.1]: 
2021-02-04T23:58:12.325045+00:00 app[web.1]: 
2021-02-04T23:58:12.325046+00:00 app[web.1]: Error running dash_docs/chapters/dash_vtk/examples/t01_volume_rendering.py
2021-02-04T23:58:12.325046+00:00 app[web.1]: ============================================================================
2021-02-04T23:58:12.325266+00:00 app[web.1]: Traceback (most recent call last):
2021-02-04T23:58:12.325273+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/vtk/vtkOpenGLKit.py", line 5, in <module>
2021-02-04T23:58:12.325442+00:00 app[web.1]:     from .vtkOpenGLKitPython import *
2021-02-04T23:58:12.325462+00:00 app[web.1]: ImportError: libSM.so.6: cannot open shared object file: No such file or directory
2021-02-04T23:58:12.325466+00:00 app[web.1]: 
2021-02-04T23:58:12.325466+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-02-04T23:58:12.325467+00:00 app[web.1]: 
2021-02-04T23:58:12.325467+00:00 app[web.1]: Traceback (most recent call last):
2021-02-04T23:58:12.325470+00:00 app[web.1]:   File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2021-02-04T23:58:12.325630+00:00 app[web.1]:     sys.exit(run())
2021-02-04T23:58:12.325633+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
2021-02-04T23:58:12.325763+00:00 app[web.1]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2021-02-04T23:58:12.325788+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
2021-02-04T23:58:12.325957+00:00 app[web.1]:     super(Application, self).run()
2021-02-04T23:58:12.325979+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
2021-02-04T23:58:12.326118+00:00 app[web.1]:     Arbiter(self).run()
2021-02-04T23:58:12.326119+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 60, in __init__
2021-02-04T23:58:12.326249+00:00 app[web.1]:     self.setup(app)
2021-02-04T23:58:12.326253+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 120, in setup
2021-02-04T23:58:12.326385+00:00 app[web.1]:     self.app.wsgi()
2021-02-04T23:58:12.326388+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-02-04T23:58:12.326528+00:00 app[web.1]:     self.callable = self.load()
2021-02-04T23:58:12.326532+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2021-02-04T23:58:12.326659+00:00 app[web.1]:     return self.load_wsgiapp()
2021-02-04T23:58:12.326664+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2021-02-04T23:58:12.326771+00:00 app[web.1]:     return util.import_app(self.app_uri)
2021-02-04T23:58:12.326776+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2021-02-04T23:58:12.326980+00:00 app[web.1]:     __import__(module)
2021-02-04T23:58:12.327001+00:00 app[web.1]:   File "/app/index.py", line 3, in <module>
2021-02-04T23:58:12.327110+00:00 app[web.1]:     from dash_docs.run import app, server
2021-02-04T23:58:12.327111+00:00 app[web.1]:   File "/app/dash_docs/run.py", line 10, in <module>
2021-02-04T23:58:12.327262+00:00 app[web.1]:     from .import chapter_index
2021-02-04T23:58:12.327266+00:00 app[web.1]:   File "/app/dash_docs/chapter_index.py", line 3, in <module>
2021-02-04T23:58:12.327386+00:00 app[web.1]:     from .import chapters
2021-02-04T23:58:12.327391+00:00 app[web.1]:   File "/app/dash_docs/chapters/__init__.py", line 15, in <module>
2021-02-04T23:58:12.327492+00:00 app[web.1]:     from .import dash_vtk
2021-02-04T23:58:12.327497+00:00 app[web.1]:   File "/app/dash_docs/chapters/dash_vtk/__init__.py", line 6, in <module>
2021-02-04T23:58:12.327609+00:00 app[web.1]:     from .import index
2021-02-04T23:58:12.327614+00:00 app[web.1]:   File "/app/dash_docs/chapters/dash_vtk/index.py", line 9, in <module>
2021-02-04T23:58:12.327724+00:00 app[web.1]:     examples = tools.load_examples(__file__)
2021-02-04T23:58:12.327745+00:00 app[web.1]:   File "/app/dash_docs/tools.py", line 78, in load_examples
2021-02-04T23:58:12.327947+00:00 app[web.1]:     examples[filename] = load_example(full_filename, run=run)
2021-02-04T23:58:12.327950+00:00 app[web.1]:   File "/ap [...]

2021-02-05 00:08 UTC, xhlulu commented
Ok this is really weird. I added a `apt-packages` to root with the apt package needed (the exact same thing worked for deploying to dash-gallery). Also tested the docs locally, circleci tests are passing, etc.

2021-02-05 01:07 UTC, jourdain commented
Make sure to replace all `from vtk.xxx import yyy` by `from vtkmodules.xxx import yyy` in the index.py

2021-02-05 15:42 UTC, jourdain commented
See 
```
2021-02-04T23:58:12.328993+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/dash_vtk/utils/vtk.py", line 3, in <module>
2021-02-04T23:58:12.329114+00:00 app[web.1]:     from vtk.util.numpy_support import vtk_to_numpy
```

It should be 

```
from vtkmodules.util.numpy_support import vtk_to_numpy
```

Like I said, any `from vtk.xxx import yyy` should be replaced by `from vtkmodules.xxx import yyy`

2021-02-05 22:47 UTC, xhlulu commented
I don't think I can import `vtkmodules` with `vtk==8.*`:
```
venv/lib/python3.7/site-packages/dash_vtk/utils/__init__.py:1: in <module>
    from .vtk import to_mesh_state, to_volume_state, presets, preset_as_options
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    import dash_vtk
    
>   from vtkmodules.util.numpy_support import vtk_to_numpy
E   ModuleNotFoundError: No module named 'vtkmodules'

venv/lib/python3.7/site-packages/dash_vtk/utils/vtk.py:3: ModuleNotFoundError
----------------------------- Captured stdout call -----------------------------
```

2021-02-05 22:50 UTC, xhlulu commented
Aside from the `vtkmodules` error, it seems like adding a [`apt-packages` ](https://github.com/plotly/dash-docs/blob/add-dash-vtk/apt-packages) file on the root doesn't do anything. Is there somewhere specific I should place it for heroku to recognize it? cc: @plotly/customer-success customer-success

2021-02-05 22:59 UTC, jcfr commented
To clarify, when using vtk 8, importing `vtk` is the correct approach.

Based on the full heroku log posted [here](https://github.com/plotly/dash-docs/pull/1091#issuecomment-773683193) the issue is:

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/vtk/vtkOpenGLKit.py", line 5, in <module>
    from .vtkOpenGLKitPython import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```

and installing the `libsm6` package should ensure the library is available (for reference see https://packages.ubuntu.com/xenial/amd64/libsm6/filelist)

2021-02-05 23:03 UTC, xhlulu commented
@jcfr Thanks for the heads up. I'm not sure if heroku allows installing apt packages by default (see this [SO thread](https://stackoverflow.com/questions/48896879/install-a-linux-package-on-heroku))

2021-02-05 23:08 UTC, jcfr commented
This means the rendering capabilities will not be available on heroku. If you would like to be able to use the other vtk functionalities (meaning everything else expect  `vtkOpenGLKit`), I suggest to add a step patching `vtk/__init__.py` file after the wheel is installed.

2021-02-05 23:44 UTC, xhlulu commented
> I suggest to add a step patching vtk/__init__.py file after the wheel is installed.

@jcfr How would you suggest approaching that?

2021-02-08 22:54 UTC, xhlulu commented
python-3.6 seems to be running on pip-18 instead of pip-20, which causes the tests to fail when it tries to install the `cryptography` library.

2021-02-09 01:51 UTC, xhlulu commented
Wow this cryptography update is causing circleCI to fail: https://github.com/pyca/cryptography/issues/5771

2021-02-09 02:28 UTC, jourdain commented
I don't like b6a35cb because it force the need to install GL and suggest a bad pattern moving forward.

```
try:
   # VTK 9+
   from vtkmodules.vtkImagingCore import vtkRTAnalyticSource
except:
  # Old VTK
  from vtk.vtkImagingCore import vtkRTAnalyticSource
```

2021-02-09 02:31 UTC, jourdain commented
I though `Cryptography` was coming from dash/test/dev but not VTK so I'm not sure why you removed vtk=9.*

2021-02-09 05:22 UTC, xhlulu commented
@plotly/customer-success python-3.6 tests are broken due to `cryptography` library (see previous link i shared). The options are to update `pip` before installing (see [this PR](https://github.com/plotly/dash-docs/pull/1093)) or fix the cryptography version to the previous release (the one based on C)

2021-02-09 13:31 UTC, cldougl commented
>@plotly/customer-success python-3.6 tests are broken due to cryptography library (see previous link i shared). The options are to update pip before installing

@xhlulu are you asking what is most desirable to fix these tests or for customers deploying apps with this package? Will this be resolved with 4.1 when pip is updated?

2021-02-09 14:33 UTC, xhlulu commented
@cldougl The `cryptography` installation problem only seems to happen in pip 18, since I can install it in pip 20.1 and above (which I believe what 4.1 has). However, I'm not sure if `dash-docs` might be built in environments where `pip` might not be up-to-date, in which case it might be better to simply fix `cryptography` to the version that's not causing any problem.

2021-02-09 14:45 UTC, chriddyp commented
@xhlulu - Heroku is on an old version of pip (pip 8 maybe?), so you'll probably need to pin cryptography to an older version in this repository.

2021-02-09 20:56 UTC, xhlulu commented
@chriddyp I pinned the requirements and seems like the tests are passing. The heroku demo also works now 🍾 

Let me know if you would like to review it. Since there's a lot of commits I can quickly mention the changes I've made in the description

2021-02-12 17:05 UTC, xhlulu commented
Can I merge this?

2021-02-12 17:19 UTC, jourdain commented
LGTM

2021-04-06 23:52 UTC, xhlulu commented
@chriddyp I can't seem to find your comment on async loading, but [I've started a PR](https://github.com/plotly/dash-vtk/pull/29) if that's blocking this from being merged.

CC: @alexcjohnson @Marc-Andre-Rivet if you wanted to review it

2021-04-06 23:53 UTC, jackparmer commented
@alexcjohnson can you please review and merge this? I don't have merge rights on this repo.

2021-04-07 00:50 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/__init__.py
> +    from .import index
```suggestion
    from . import index
```
Surprised we don't have linters complaining about this... I guess you're just copying the pattern in `chapters/__init__.py` but ideally we fix that too.

2021-04-07 00:52 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +import inspect
🔪 ?

2021-04-07 00:56 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    [Vtk.js](https://kitware.github.io/vtk-js/) on the other hand is a subset of VTK that focus on the rendering aspect of it but in the JavaScript world. Vtk.js takes the same architecture and objec
```suggestion
    [Vtk.js](https://kitware.github.io/vtk-js/) on the other hand is a subset of VTK that focuses on the rendering aspect of it but in the JavaScript world. Vtk.js takes the same architecture and object decomposition as its big brother VTK/C++ but makes it friendly to use inside your browser.
```

2021-04-07 00:57 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    Dash-vtk is enabling its users to use VTK on the server side for any data processing and provide the infrastructure to push the visualization to the client side for a better experience.
```suggestion
    Dash-vtk enables its users to use VTK on the server side for any data processing and provides the infrastructure to push the visualization to the client side for a better experience.
```

2021-04-07 00:57 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    Dash-vtk do not require VTK but can seamlessly leverage it for looking at point clouds, a CFD simulation or anything 3D mesh or 3D images related.
```suggestion
    Dash-vtk does not require VTK but can seamlessly leverage it for looking at point clouds, a CFD simulation or anything 3D mesh or 3D images related.
```

2021-04-07 00:59 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __scrollEnabled__: True/False # Some action could also be trigger by scroll
```suggestion
    - __scrollEnabled__: True/False # Some action could also be triggered by scroll
```

2021-04-07 00:59 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __Pan__: Will pan the object on the plan normal to the camera
```suggestion
    - __Pan__: Will pan the object on the plane normal to the camera
```

2021-04-07 00:59 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __ZoomToMouse__: Will zoom while keeping the location that was initialy under the mouse at the same spot
```suggestion
    - __ZoomToMouse__: Will zoom while keeping the location that was initially under the mouse at the same spot
```

2021-04-07 01:00 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    A representation is responsible to convert a __DataSource__ into something visual that will be available inside the __View__.
```suggestion
    A representation is responsible for converting a __DataSource__ into something visual that will be available inside the __View__.
```

2021-04-07 01:02 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __Algorithm__: It allow you to instanciate a vtk.js algorithm that could either be a filter (vtkWarpScalar) or a source (vtkLineSource, vtkConeSource, vtkPlaneSource, vtkSphereSource, vtkCylind
```suggestion
    - __Algorithm__: Allows you to instantiate a vtk.js algorithm that could either be a filter (vtkWarpScalar) or a source (vtkLineSource, vtkConeSource, vtkPlaneSource, vtkSphereSource, vtkCylinderSource).
```

2021-04-07 01:03 UTC, xhlulu commented on dash_docs/chapters/dash_vtk/index.py
> +import inspect
🔪 'd

2021-04-07 01:04 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __ImageData__: An ImageData is what I've been calling a 3D image so far. This element will let you define each piece that compose a 3D image.
```suggestion
    - __ImageData__: What we've been calling a 3D image so far. This element will let you define each piece that comprises a 3D image.
```

2021-04-07 01:05 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __PolyData__: A PolyData is a surface mesh (points, triangles...). This element will let you define the various piece of a mesh.
```suggestion
    - __PolyData__: A surface mesh (points, triangles...). This element will let you define the various piece of a mesh.
```

2021-04-07 01:05 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __Reader__: A reader is similar to an __Algorithm__ except that readers have a common set of API and this element let you leverage those.
```suggestion
    - __Reader__: Similar to an __Algorithm__ except that readers have a common API and this element lets you leverage those.
```

2021-04-07 01:07 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __ShareDataSet__: This element allow you to capture any __DataSource__ and make it available into another processing pipeline or representation without duplicating the data that get sent from t
```suggestion
    - __ShareDataSet__: Allows you to capture any __DataSource__ and make it available in another processing pipeline or representation without duplicating the data that gets sent from the server to the client.
```

2021-04-07 01:08 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __Mesh__: This element is similar to __PolyData__ except that it has a Python helper function that goes with it which will help you map a __vtkDataSet__ into a single property of the __Mesh__.
```suggestion
    - __Mesh__: Similar to __PolyData__ except that it has a Python helper function to help you map a __vtkDataSet__ into a single property of the __Mesh__.
```

2021-04-07 01:08 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __Volume__: This element is similar to __ImageData__ except that it has a Python helper function that goes with it which will help you map a __vtkImageData__ into a single property of the __Vol
```suggestion
    - __Volume__: Similar to __ImageData__ except that it has a Python helper function to help you map a __vtkImageData__ into a single property of the __Volume__.
```

2021-04-07 01:17 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    mesh_state = to_mesh_state(dataset)
```suggestion
    mesh_state = dash_vtk.utils.to_mesh_state(dataset)
```
unless you want to show its import statement

2021-04-07 01:19 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    But in our usecase here we are going to explain some of the fondation of those data structure so you could understand how you could create them by hand if you wanted to.
```suggestion
    Here we explain some of the foundation of those data structures so you could create them by hand if you wanted to.
```

2021-04-07 01:19 UTC, xhlulu commented on dash_docs/chapters/dash_vtk/index.py
> +    mesh_state = to_mesh_state(dataset)
The code snippets explicitly import it so I guess we could be consistent in that way:

```suggestion
    from dash_vtk.utils import to_mesh_state
    mesh_state = to_mesh_state(dataset)
```

2021-04-07 01:20 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    An Image data is an implicit grid that is axis aligned like shown in the picture below.
```suggestion
    An ImageData is an implicit grid that is axis aligned as shown in the picture below.
```

2021-04-07 01:22 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    A Poly data is a surface mesh that is composed of `points` and `cells`. A polydata can be composed of various types of cells listed below:
```suggestion
    A PolyData is a surface mesh composed of `points` and `cells`. The cells can be:
```

2021-04-07 01:22 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __verts__: Vertex or point that we want to see as a tiny square on the screen
```suggestion
    - __verts__: Vertex or point to show as a tiny square on the screen
```

2021-04-07 01:23 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __polys__: Polygones which are convex surface such as a triangle, rectangle, circle...
```suggestion
    - __polys__: Polygons which are convex surfaces such as triangles, rectangles, circles...
```

2021-04-07 01:24 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __strips__: Triangle strips is a way to combine efficiently triangles together with no repetition in points connectivity
```suggestion
    - __strips__: Triangle strips efficiently combine triangles together with no repeated points just for connectivity
```

2021-04-07 01:27 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The way cells are defined is via an index based array that map to a given point index. For example let's pretend you want to create a line that has 2 segments, you will need at least 3 points def
```suggestion
    The way cells are defined is via an index-based array that maps to a given point index. For example let's pretend you want to create a line with 2 segments, you will need at least 3 points defined in the `points` array. If those points are defined first in your `points` array, then the `lines` array should be filled as follows:
```

2021-04-07 01:28 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    In case you want to create 2 lines independant from each other, you can do it as follow:
```suggestion
    To create 2 lines independent of each other, you can do it as follows:
```

2021-04-07 01:31 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The `dash_vtk.PolyData` element has an additional property to automatically generate cells based on some assumption of the order of the points defined in the `points` array. That property is name
```suggestion
    The `dash_vtk.PolyData` element has an additional property to automatically generate cells based on some assumption of the order of the points defined in the `points` array. That property is named __connectivity__ and defaults to `manual`, meaning no automatic action is taken. But that property can be set to `points` to automatically set the vertex to actually see the points provided or `triangles` which uses each set of 3 consecutive points to create a triangle and finally `strips` which consumes all the points in a single strip of triangles.
```

2021-04-07 01:32 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The diagram below try to explain the difference between fields located on points vs cells in term of rendering but it also trully has a different meaning based on the type of data that you have.
```suggestion
    The diagram below tries to explain the difference between fields located on points vs cells in term of rendering, but it also truly has a different meaning based on the type of data that you have.
```

2021-04-07 01:32 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The example below show you how you can attach fields to a dataset (PolyData and/or ImageData).
```suggestion
    The example below shows how to attach fields to a dataset (PolyData and/or ImageData).
```

2021-04-07 01:33 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    In VTK a representation is composed of an [__Actor__](https://kitware.github.io/vtk-js/api/Rendering_Core_Actor.html), a [__Mapper__](https://kitware.github.io/vtk-js/api/Rendering_Core_Mapper.ht
```suggestion
    In VTK a representation is composed of an [__Actor__](https://kitware.github.io/vtk-js/api/Rendering_Core_Actor.html), a [__Mapper__](https://kitware.github.io/vtk-js/api/Rendering_Core_Mapper.html) and a [__Property__](https://kitware.github.io/vtk-js/api/Rendering_Core_Property.html). Each of those objects can be configured using the __actor__, __mapper__ and __property__ arguments of the __GeometryRepresentation__.
```

2021-04-07 01:34 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The list below show you the default values used for each argument:
```suggestion
    The list below shows the default values for each argument:
```

2021-04-07 01:38 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    GlyphRepresentation let you use a source as a Glyph which will then be cloned and position at every points of another source. The properties available on the __GlyphRepresentation__ let you tune
```suggestion
    GlyphRepresentation lets you use a source as a Glyph which will then be cloned and positioned at every point of another source. The properties available on the __GlyphRepresentation__ let you tune the way you want to render your geometry.
```

2021-04-07 01:39 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    In VTK a representation is composed of an [__Actor__](https://kitware.github.io/vtk-js/api/Rendering_Core_Actor.html), a [__Mapper__](https://kitware.github.io/vtk-js/api/Rendering_Core_Glyph3DMa
```suggestion
    In VTK a representation is composed of an [__Actor__](https://kitware.github.io/vtk-js/api/Rendering_Core_Actor.html), a [__Mapper__](https://kitware.github.io/vtk-js/api/Rendering_Core_Glyph3DMapper.html) and a [__Property__](https://kitware.github.io/vtk-js/api/Rendering_Core_Property.html). Each of those objects can be configured using the __actor__, __mapper__ and __property__ arguments of the __GlyphRepresentation__.
```

2021-04-07 01:40 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The list below show you the default values used for each argument:
```suggestion
    The list below shows the default values for each argument:
```

2021-04-07 01:40 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    An example of the __GlyphRepresentation__ could be for creating a spicky sphere by positioning cones normal to the sphere.
```suggestion
    An example of the __GlyphRepresentation__ could be creating a spiky sphere by positioning cones normal to the sphere.
```

2021-04-07 01:41 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    In VTK a representation is composed of an [__Volume__](https://kitware.github.io/vtk-js/api/Rendering_Core_Volume.html), a [__Mapper__](https://kitware.github.io/vtk-js/api/Rendering_Core_VolumeM
```suggestion
    In VTK a representation is composed of an [__Volume__](https://kitware.github.io/vtk-js/api/Rendering_Core_Volume.html), a [__Mapper__](https://kitware.github.io/vtk-js/api/Rendering_Core_VolumeMapper.html) and a [__Property__](https://kitware.github.io/vtk-js/api/Rendering_Core_VolumeProperty.html). Each of those objects can be configured using the __actor__, __mapper__ and __property__ arguments of the __GeometryRepresentation__.
```

2021-04-07 01:41 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The list below show you the default values used for each argument:
```suggestion
    The list below shows the default values for each argument:
```

2021-04-07 01:43 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    Because it can be combersome and difficult to properly configure your volume rendering properties, it is convinient to add as first child to that representation a __VolumeController__ which will
```suggestion
    Because it can be cumbersome and difficult to properly configure your volume rendering properties, it is convenient to add as first child to that representation a __VolumeController__ which will give you a UI to drive some of those parameters while also providing better defaults for your ImageData.
```

2021-04-07 01:43 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The __VolumeController__ provide a convinient UI element to control your Volume Rendering settings and can be tuned with the following set of properties:
```suggestion
    The __VolumeController__ provide a convenient UI element to control your Volume Rendering settings and can be tuned with the following set of properties:
```

2021-04-07 01:44 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The __SliceRepresentation__ let you see a slice within a 3D image. That slice can be along i,j,k or x,y,z if your volume contains an orientation matrix.
```suggestion
    The __SliceRepresentation__ lets you see a slice within a 3D image. That slice can be along i,j,k or x,y,z if your volume contains an orientation matrix.
```

2021-04-07 01:44 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The following set of properties let you pick which slice you want to see. Only 1 of those property can be used at a time.
```suggestion
    The following set of properties lets you pick which slice you want to see. Only one of those properties can be used at a time.
```

2021-04-07 01:46 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The __PointCloudRepresentation__ is just a helper using the following structure to streamline rendering a point cloud dataset. The code snippet below is not fully accurate but it should provide y
```suggestion
    The __PointCloudRepresentation__ is just a helper using the following structure to streamline rendering a point cloud dataset. The code snippet below is not complete but it should provide you with some understanding of the kind of simplification that is happening under the hood.
```

2021-04-07 01:46 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The set of convinient properties are as follow:
```suggestion
    The set of convenient properties are as follows:
```

2021-04-07 01:47 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __rgb__ / __rgba__ / __scalars__ = [...] let you define the field you want to color your point cloud with. The rgb(a) expect numbers up to 255 for each component of Red Green Blue Alpha.
```suggestion
    - __rgb__ / __rgba__ / __scalars__ = [...] let you define the field you want to color your point cloud with. The rgb(a) expects numbers up to 255 for each component: Red Green Blue (Alpha).
```

2021-04-07 01:49 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The __VolumeDataRepresentation__ is just a helper using the following structure to streamline rendering a volume. The code snippet below is not fully accurate but it should provide you with some
```suggestion
    The __VolumeDataRepresentation__ is just a helper using the following structure to streamline rendering a volume. The code snippet below is not complete but it should provide you with some understanding of the kind of simplification that is happening under the hood.
```

2021-04-07 01:49 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The set of convinient properties are as follow:
```suggestion
    The set of convenient properties are as follows:
```

2021-04-07 01:50 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The __Mesh__ element expect a single __state__ property that is internaly split into 2 elements to represent the geometry and the field that you want to optionally attach to your mesh. The struct
```suggestion
    The __Mesh__ element expects a single __state__ property that is internally split into 2 elements to represent the geometry and the field that you want to optionally attach to your mesh. The structure could be defined as follows:
```

2021-04-07 01:51 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The __Volume__ element expect a single __state__ property that is internaly split into 2 elements to represent the geometry and the field that you want to optionally attach to your mesh. The stru
```suggestion
    The __Volume__ element expects a single __state__ property that is internally split into 2 elements to represent the geometry and the field that you want to optionally attach to your mesh. The structure could be defined as follows:
```

2021-04-07 01:51 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    This element allow you to create and configure a vtk.js class. This element expect only 2 properties:
```suggestion
    This element allows you to create and configure a vtk.js class. This element expect only 2 properties:
```

2021-04-07 01:52 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The current [list of classes](https://github.com/Kitware/react-vtk-js/blob/master/src/AvailableClasses.js#L4-L15) that could be instantiate are as follow:
```suggestion
    The current [list of classes](https://github.com/Kitware/react-vtk-js/blob/master/src/AvailableClasses.js#L4-L15) available to instantiate are:
```

2021-04-07 01:54 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    - __state__: You will have to look on which property is available for your selected vtkClass.
```suggestion
    - __state__: See the references above for the properties available for each vtkClass.
```

2021-04-07 01:54 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The following example use a vtk source in vtk.js to generate a mesh
```suggestion
    The following example uses a vtk source in vtk.js to generate a mesh
```

2021-04-07 01:55 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    This element is similar to the __Algorithm__ one except that it focus on vtk.js readers by allowing to leverage their custom API.
```suggestion
    This element is similar to the __Algorithm__ except that it focuses on vtk.js readers by allowing you to leverage their custom API.
```

2021-04-07 01:56 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    A reader expect like an __Algorithm__ a __vtkClass__ among the one [listed below](https://github.com/Kitware/react-vtk-js/blob/master/src/AvailableClasses.js#L17-L24):
```suggestion
    Like __Algorithm__, a reader expects a __vtkClass__ among those [listed below](https://github.com/Kitware/react-vtk-js/blob/master/src/AvailableClasses.js#L17-L24):
```

2021-04-07 01:56 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    Then you should use one of the property below to feed the reader with some data:
```suggestion
    Then use one of the properties below to feed the reader some data:
```

2021-04-07 01:59 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    This element does not affect the dataset or else, but it allow the JavaScript side to reuse an existing __vtkDataSet__ for another __Representation__ or __filter__.
or else what? also allow -> allows

2021-04-07 02:00 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The only property expected in a __ShareDataSet__ is a name to properly reference it accross various location. By default a __name__ is provided so, in the case of only one _dataset_, you would no
```suggestion
    The only property expected in a __ShareDataSet__ is a name to properly reference it elsewhere. By default a __name__ is provided so, in the case of only one _dataset_, you would not even need to specify this property.
```

2021-04-07 02:02 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    The following example show how you can create a view with 1 __Volume__ and 4 representation of it.
```suggestion
    The following example shows how to create a view with one __Volume__ and four representations of it.
```

2021-04-07 02:02 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    Then we made several example using plain VTK for both a CFD example and some medical ones.
```suggestion
    Then we made several examples using plain VTK for both a CFD example and some medical ones.
```

2021-04-07 02:03 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    This example leverage plain VTK on the server side while providing UI controls in __dash__ and leverage __dash_vtk__ to enable local rendering of dynamically computed streamlines inside a wind-tu
```suggestion
    This example leverages plain VTK on the server side while providing UI controls in __dash__ and leverages __dash_vtk__ to enable local rendering of dynamically computed streamlines inside a wind tunnel.
```

2021-04-07 15:55 UTC, alexcjohnson commented on dash_docs/chapters/dash_vtk/index.py
> +    mesh_state = to_mesh_state(dataset)
yep, that's what I meant by "unless you want to show its import statement" - whichever you prefer is fine, just want to make sure the code stands on its own.

2021-04-07 16:15 UTC, xhlulu commented on dash_docs/chapters/dash_vtk/index.py
> +    This element does not affect the dataset or else, but it allow the JavaScript side to reuse an existing __vtkDataSet__ for another __Representation__ or __filter__.
```suggestion
    This element does not affect the dataset, but it allows the JavaScript side to reuse an existing __vtkDataSet__ for another __Representation__ or __filter__.
```

@jourdain Is the suggestion okay?

2021-04-07 16:20 UTC, jourdain commented on dash_docs/chapters/dash_vtk/index.py
> +    This element does not affect the dataset or else, but it allow the JavaScript side to reuse an existing __vtkDataSet__ for another __Representation__ or __filter__.
yes

2021-04-14 13:40 UTC, jdamiba commented
@xhlulu Just a reminder that we will need to edit the `requirements.txt` file here to point to the the PyPi version of `dash-vtk` instead of a reference to GitHub once the `lazy-loading` branch has been merged to master and a new release of `dash-vtk` has been created.

2021-04-16 19:39 UTC, jdamiba commented
This PR looks good to me 💃🏿 

I tested that the async functionality works on the Heroku review app.

2021-04-16 19:59 UTC, rpkyle requested changes
Just a few minor comments, otherwise this looks OK to me.

2021-04-16 19:59 UTC, rpkyle commented on tests/integration/test_page_menu.py
> +        'Dash Python User Guide',
```suggestion
        'Dash for Python User Guide',
```

2021-04-16 20:04 UTC, jdamiba commented on tests/integration/test_page_menu.py
> +        'Dash Python User Guide',
This change is outside of the scope of this PR- if we want to reword the heading let's do it in a separate PR where we change it both here in the test and in the markup so that CI keeps passing.

2021-04-16 20:05 UTC, xhlulu commented on dash_docs/chapters/dash_vtk/examples/t01_volume_rendering.py
> +        # + Setup good default at startup
@jourdain ☝️

2021-04-16 20:05 UTC, xhlulu commented on dash_docs/chapters/dash_vtk/examples/t02_imagedata.py
> +
@rpkyle that's handled internally by `dash_vtk` I believe

2021-04-16 20:05 UTC, xhlulu commented on dash_docs/chapters/dash_vtk/examples/t03_polydata.py
> +
Same response as above.

2021-04-16 20:12 UTC, jdamiba commented on dash_docs/chapters/dash_vtk/examples/t02_imagedata.py
> +
@rpkyle Note that this example piece of code is importing from the `vtkmodules` library, not `dash_vtk`. 

No compatibility check needed if the import is not from `vtkmodules`.

2021-04-16 20:15 UTC, rpkyle commented on tests/integration/test_page_menu.py
> +        'Dash Python User Guide',
:woman_dancing:

2021-04-16 20:16 UTC, rpkyle approved these changes

2021-04-16 20:20 UTC, rpkyle commented
Once we can get the tests passing, :woman_dancing:

2021-04-16 20:44 UTC, jourdain commented on dash_docs/chapters/dash_vtk/examples/t01_volume_rendering.py
> +        # + Setup good default at startup
The values get computed based on the volume data and geometry. While the default values are static and therefore will have little chance to produce a good result across a various set of volumes. 

Normally an advanced user will update the parameters the way he wants the volume to be rendered. But if you don't know what the data is about, using the controller would give you a reasonable rendering. We could recreate the computation of those values inside the volume representation but it will have to be under a property like `viz-profile="auto"` or something equivalent.

2021-04-16 20:47 UTC, jourdain commented on dash_docs/chapters/dash_vtk/examples/t01_volume_rendering.py
> +        # + Setup good default at startup
The magic number computation is happening [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/UI/VolumeController/index.js#L35-L106)

2021-04-16 20:50 UTC, jourdain commented on dash_docs/chapters/dash_vtk/examples/t02_imagedata.py
> +
`vtkmodules` is only available for 9+, so the check should be made...

2021-04-16 21:53 UTC, merged